//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fingerprint: String,
    pub fighter: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::devices_locations::Entity")]
    DevicesLocations,
}

impl Related<super::devices_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DevicesLocations.def()
    }
}

impl Related<super::locations::Entity> for Entity {
    fn to() -> RelationDef {
        super::devices_locations::Relation::Locations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::devices_locations::Relation::Devices.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
