//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::devices::Entity as Devices;
pub use super::devices_locations::Entity as DevicesLocations;
pub use super::locations::Entity as Locations;
