name: deploy server to shuttle

on:
  push:
    branches:
      - "ebobo"
    paths:
      - "server/**"
      - "shared/**"
      - ".github/workflows/shuttle.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          working-directory: ./server
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}